apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-stress
  namespace: stress
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-stress
        role: k8s-stress
    spec:
      containers:
        - name: k8s-stress
          image: chriskranz/cpu-stress
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 40000m
              memory: 40960Mi
            limits:
              cpu: 45000m
              memory: 41000Mi
