kind: Template
apiVersion: v1
labels:
  template: database
metadata:
  name: database
  annotations:
    openshift.io/display-name: "VOTEAPP-PHP-MARIADB" 
    description: "An example of PHP web based application VOTEAPP with a MariaDB database."
    tags: "database"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      database: db
    name: database
  spec:
    replicas: 1
    selector:
      database: db
      deploymentconfig: database
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          database: db 
          deploymentconfig: database
      spec:
        containers:
        - env:
          - name: DB_NAME
            value: vote_db
          - name: DB_PASSWD
            value: india@123
          - name: DB_USER
            value: root
          image: 'docker-registry.default.svc:5000/openshift/votedb:latest'
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 45
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: database
          ports:
          - containerPort: 3306
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$DB_PASSWD" mysql -h 127.0.0.1 -u $DB_USER -D $DB_NAME
                -e 'SELECT 1'
            timeoutSeconds: 2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
#- apiVersion: v1
#  kind: Service
#  metadata:
#    labels:
#      database: db
#    name: database
#  spec:
#    ports:
#    - name: 3306-tcp
#      port: 3306
#      protocol: TCP
#      targetPort: 3306
#    selector:
#      database: db 
#      deploymentconfig: database
