kind: Template
apiVersion: v1
labels:
  template: frontend
metadata:
  name: frontend
  annotations:
    openshift.io/display-name: "VOTEAPP-PHP-MARIADB" 
    description: "An example of PHP web based application VOTEAPP with a MariaDB database."
    tags: "front-end"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      frontend: web
    name: frontend
  spec:
    replicas: 1
    selector:
      frontend: web
      deploymentconfig: frontend
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          frontend: web
          deploymentconfig: frontend
      spec:
        containers:
        - env:
          - name: DB_NAME
            value: vote_db
          - name: DB_PASSWD
            value: india@123
          - name: DB_USER
            value: root
          - name: DB_ADDR
            value: backend.backend.svc.local
          image: 'docker-registry.default.svc:5000/openshift/voteweb:latest'
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 45
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: frontend
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      frontend: web
    name: frontend
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      frontend: web
      deploymentconfig: frontend
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      frontend: web
    name: frontend
  spec:
    host: ""
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: frontend
