---
apiVersion: v1
kind: Secret
metadata:
  name: sysdigcloud-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjM2x6WkdsbksyZHBjbWx5WVdwZmNtRnFZWGRoZERwWE1VZFZXalpPUnpFNU5VUlNWRVpUUTFoT1JEVllOMXBITWswM09UZFZWakF5T0ZCQ1ZGWTFWMDg0TWtWVU5VUllXa3BDTmxkWlFVMDJVMUZVTlVKSCIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
