apiVersion: v1
kind: Route
metadata:
  name: collector-passthrough-ssl
spec:
  # Note: this dns name MUST be different from the Api dns name
  host: ocp.192.168.54.151.nip.io
  to:
    kind: Service
    name: sysdigcloud-collector
  tls:
    termination: passthrough
  port:
    targetPort: 6443
